# Generated by Django 5.2.6 on 2025-09-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_subject_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='status',
        ),
    ]
